# Generated by Django 5.0.7 on 2024-12-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(default=False),
        ),
    ]
