# Generated by Django 4.2.17 on 2024-12-25 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_is_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
    ]
