# Generated by Django 4.2.17 on 2024-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_remove_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
