# Generated by Django 4.2.17 on 2024-12-25 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_email_verified_user_verification_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_code",
        ),
    ]
