# Generated by Django 5.0.7 on 2024-12-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_user_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
