# Generated by Django 4.2.17 on 2024-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_pendinguser"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="is_client",
            field=models.BooleanField(default=False),
        ),
    ]
