# Generated by Django 4.2.17 on 2024-12-27 15:42

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_pendinguser_is_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendinguser",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=250,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator],
            ),
        ),
    ]
