# Generated by Django 4.2.17 on 2024-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="code_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
