# Generated by Django 4.2.17 on 2024-12-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_pendinguser_code_expiration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
