# Generated by Django 4.2.17 on 2024-12-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_user_code_expiration_user_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
